In [2]:
import numpy as np

In [3]:
l = [1,2,3,4,5]

In [4]:
ar=np.array(l)

In [5]:
type(ar)

numpy.ndarray

In [6]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [7]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [8]:
a =[2,3,4]
np.asanyarray(a)

array([2, 3, 4])

In [9]:
b =np.matrix(l)

In [10]:
b

matrix([[1, 2, 3, 4, 5]])

In [11]:
np.asanyarray(b)

matrix([[1, 2, 3, 4, 5]])

In [12]:
a = np.array(l)

In [13]:
a

array([1, 2, 3, 4, 5])

In [14]:
c = a

In [15]:
c 

array([1, 2, 3, 4, 5])

In [16]:
c [0]

1

In [17]:
c[0]=100

In [18]:
c[0]

100

In [19]:
a

array([100,   2,   3,   4,   5])

In [20]:
d = np.copy(a)

In [21]:
d

array([100,   2,   3,   4,   5])

In [22]:
a[1]=400

In [23]:
d

array([100,   2,   3,   4,   5])

In [24]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [25]:
iterable=(i*i for i in range(5))

In [26]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [27]:
np.fromstring('234 5677',sep=' ')

array([ 234., 5677.])

In [28]:
np.fromstring('4,5',sep=',')

array([4., 5.])

In [29]:
l = [2,3,4,5,6]
ar=np.array(l)

In [30]:
ar

array([2, 3, 4, 5, 6])

In [31]:
ar.ndim

1

In [32]:
ar2 = np.array([[1,2,3,4],[3,4,5,7]])

In [33]:
ar2.ndim

2

In [34]:
ar2.size

8

In [35]:
ar.shape

(5,)

In [36]:
ar2.shape

(2, 4)

In [37]:
ar.dtype

dtype('int64')

In [38]:
ar2.dtype

dtype('int64')

In [39]:
ar22 = np.array([(1.4,34,56),(23,45,67)])

In [40]:
ar22

array([[ 1.4, 34. , 56. ],
       [23. , 45. , 67. ]])

In [41]:
ar22.dtype

dtype('float64')

In [42]:
list(range(5))

[0, 1, 2, 3, 4]

In [43]:
list(np.arange(2.3,5.6,0.5))

[2.3, 2.8, 3.3, 3.8, 4.3, 4.8, 5.3]

In [44]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [45]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [46]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
np.zeros((3,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [48]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [49]:
np.empty((3,5))

array([[4.68838323e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 6.32404027e-322]])

In [50]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [51]:
np.linspace(2,4,10)

array([2.        , 2.22222222, 2.44444444, 2.66666667, 2.88888889,
       3.11111111, 3.33333333, 3.55555556, 3.77777778, 4.        ])

In [52]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [53]:
np.logspace(2,5,10,base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [54]:
arr=np.random.randn(3,4)

In [55]:
import pandas as pd

In [56]:
pd.DataFrame(arr)

0         1         2         3
0  0.116570  0.739419 -0.427726 -0.182258
1 -1.729369  0.960321 -0.252267 -0.166334
2 -2.253131  1.860355 -0.614124  2.018498

In [57]:
np.random.rand(3,4)

array([[0.3540057 , 0.61199318, 0.1876145 , 0.50618598],
       [0.060422  , 0.78469912, 0.89161389, 0.29984152],
       [0.47555453, 0.10647859, 0.73021072, 0.03253417]])

In [58]:
a=np.random.randint(3,101,(3,4))

In [59]:
pd.DataFrame(a)

0   1   2   3
0  33  16  51  82
1  88  91  88  80
2   4  28  11  37

In [60]:
arr = np.random.rand(3,4)

In [61]:
arr

array([[0.95507702, 0.66737899, 0.08931177, 0.8745505 ],
       [0.66615649, 0.08946898, 0.07668998, 0.45302513],
       [0.39953505, 0.92800293, 0.39038328, 0.9671329 ]])

In [62]:
arr1=arr.reshape(6,2)

In [63]:
arr1

array([[0.95507702, 0.66737899],
       [0.08931177, 0.8745505 ],
       [0.66615649, 0.08946898],
       [0.07668998, 0.45302513],
       [0.39953505, 0.92800293],
       [0.39038328, 0.9671329 ]])

In [64]:
arr1[0][1]

0.6673789858658841

In [65]:
arr=np.random.randint(1,100,(5,5))

In [66]:
arr


array([[73, 91, 38,  6,  1],
       [54, 84,  9, 63, 53],
       [18, 43, 73, 17, 93],
       [92, 68, 90, 19, 59],
       [64, 68, 33, 45, 86]])

In [67]:
arr[arr>50]

array([73, 91, 54, 84, 63, 53, 73, 93, 92, 68, 90, 59, 64, 68, 86])

In [68]:
arr

array([[73, 91, 38,  6,  1],
       [54, 84,  9, 63, 53],
       [18, 43, 73, 17, 93],
       [92, 68, 90, 19, 59],
       [64, 68, 33, 45, 86]])

In [69]:
arr[2:4,3:5]

array([[17, 93],
       [19, 59]])

In [70]:
arr[1][1]=600

In [71]:
arr

array([[ 73,  91,  38,   6,   1],
       [ 54, 600,   9,  63,  53],
       [ 18,  43,  73,  17,  93],
       [ 92,  68,  90,  19,  59],
       [ 64,  68,  33,  45,  86]])

In [72]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [73]:
arr1+arr2

array([[2, 4, 3],
       [2, 4, 3],
       [3, 4, 2]])

In [74]:
arr1-arr2

array([[ 0,  0, -1],
       [ 0,  0,  1],
       [ 1,  0,  0]])

In [75]:
arr1/arr2

array([[1. , 1. , 0.5],
       [1. , 1. , 2. ],
       [2. , 1. , 1. ]])

In [76]:
arr1*arr2

array([[1, 4, 2],
       [1, 4, 2],
       [2, 4, 1]])

In [77]:
arr1@arr2

array([[ 4,  8,  5],
       [ 5, 10,  6],
       [ 5, 10,  7]])

In [78]:
arr1/0

/tmp/ipykernel_1324/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [79]:
arr1+100

array([[101, 102, 101],
       [101, 102, 102],
       [102, 102, 101]])

In [80]:
arr1**2

array([[1, 4, 1],
       [1, 4, 4],
       [4, 4, 1]])

In [81]:
arr=np.zeros((4,4))

In [82]:
row = np.array([1,2,3,4])

In [83]:
arr=arr+row

In [84]:
arr.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [85]:
arr9 = np.random.randint(1,4,(3,4))

In [86]:
arr9

array([[3, 2, 2, 3],
       [3, 3, 1, 1],
       [1, 3, 2, 3]])

In [87]:
np.sqrt(arr9)

array([[1.73205081, 1.41421356, 1.41421356, 1.73205081],
       [1.73205081, 1.73205081, 1.        , 1.        ],
       [1.        , 1.73205081, 1.41421356, 1.73205081]])

In [88]:
np.exp(arr9)

array([[20.08553692,  7.3890561 ,  7.3890561 , 20.08553692],
       [20.08553692, 20.08553692,  2.71828183,  2.71828183],
       [ 2.71828183, 20.08553692,  7.3890561 , 20.08553692]])

In [89]:
np.log10(arr9)

array([[0.47712125, 0.30103   , 0.30103   , 0.47712125],
       [0.47712125, 0.47712125, 0.        , 0.        ],
       [0.        , 0.47712125, 0.30103   , 0.47712125]])

In [90]:
arr1.flatten()

array([1, 2, 1, 1, 2, 2, 2, 2, 1])

In [91]:
np.expand_dims(arr1,axis=0)

array([[[1, 2, 1],
        [1, 2, 2],
        [2, 2, 1]]])

In [92]:
np.squeeze(arr1)

array([[1, 2, 1],
       [1, 2, 2],
       [2, 2, 1]])

In [93]:
data = np.array([[1],[2],[4]])

In [94]:
data

array([[1],
       [2],
       [4]])

In [95]:
np.squeeze(data)

array([1, 2, 4])

In [96]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 1, 1, 1])

In [97]:
np.roll(arr1,shift=2)

array([[2, 1, 1],
       [2, 1, 1],
       [2, 2, 2]])

In [98]:
np.diag(arr1)

array([1, 2, 1])

In [99]:
#binary operation

In [100]:
arr1 = np.random.randint(1,10,(3,4))
arr1

array([[7, 9, 5, 6],
       [3, 1, 7, 1],
       [5, 7, 2, 9]])

In [101]:
arr2 = np.random.randint(1,10,(3,4))
arr2

array([[6, 8, 3, 1],
       [4, 7, 5, 7],
       [9, 2, 9, 8]])

In [102]:
arr1+arr2

array([[13, 17,  8,  7],
       [ 7,  8, 12,  8],
       [14,  9, 11, 17]])

In [103]:
arr1*arr2

array([[42, 72, 15,  6],
       [12,  7, 35,  7],
       [45, 14, 18, 72]])

In [104]:
arr1/arr2

array([[1.16666667, 1.125     , 1.66666667, 6.        ],
       [0.75      , 0.14285714, 1.4       , 0.14285714],
       [0.55555556, 3.5       , 0.22222222, 1.125     ]])

In [105]:
arr1-arr2

array([[ 1,  1,  2,  5],
       [-1, -6,  2, -6],
       [-4,  5, -7,  1]])

In [106]:
arr1%arr2

array([[1, 1, 2, 0],
       [3, 1, 2, 1],
       [5, 1, 2, 1]])

In [107]:
arr1|arr2

array([[ 7,  9,  7,  7],
       [ 7,  7,  7,  7],
       [13,  7, 11,  9]])

In [108]:
arr1&arr2

array([[6, 8, 1, 0],
       [0, 1, 5, 1],
       [1, 2, 0, 8]])

In [109]:
#string functiom
import numpy as np

In [110]:
arr = np.array(['sudh','kumar'])


In [111]:
np.char.upper(arr)


array(['SUDH', 'KUMAR'], dtype='<U5')

In [112]:
arr1

array([[7, 9, 5, 6],
       [3, 1, 7, 1],
       [5, 7, 2, 9]])

In [113]:
np.sin(arr1)

array([[ 0.6569866 ,  0.41211849, -0.95892427, -0.2794155 ],
       [ 0.14112001,  0.84147098,  0.6569866 ,  0.84147098],
       [-0.95892427,  0.6569866 ,  0.90929743,  0.41211849]])

In [114]:
np.cos(arr1)

array([[ 0.75390225, -0.91113026,  0.28366219,  0.96017029],
       [-0.9899925 ,  0.54030231,  0.75390225,  0.54030231],
       [ 0.28366219,  0.75390225, -0.41614684, -0.91113026]])

In [115]:
np.tan(arr1)

array([[ 0.87144798, -0.45231566, -3.38051501, -0.29100619],
       [-0.14254654,  1.55740772,  0.87144798,  1.55740772],
       [-3.38051501,  0.87144798, -2.18503986, -0.45231566]])

In [116]:
arr = np.array([4,3,5,6,7,4,56,6,7,7,8,4])

In [117]:
arr

array([ 4,  3,  5,  6,  7,  4, 56,  6,  7,  7,  8,  4])

In [118]:
np.sort(arr)

array([ 3,  4,  4,  4,  5,  6,  6,  7,  7,  7,  8, 56])

In [119]:
arr.sort()

In [120]:
arr

array([ 3,  4,  4,  4,  5,  6,  6,  7,  7,  7,  8, 56])

In [121]:
np.searchsorted(arr,56)

11

In [122]:
np.count_nonzero(arr)

12

In [123]:
#byte swap

In [124]:
arr

array([ 3,  4,  4,  4,  5,  6,  6,  7,  7,  7,  8, 56])

In [125]:
arr.byteswap()

array([ 216172782113783808,  288230376151711744,  288230376151711744,
        288230376151711744,  360287970189639680,  432345564227567616,
        432345564227567616,  504403158265495552,  504403158265495552,
        504403158265495552,  576460752303423488, 4035225266123964416])

In [127]:
import numpy.matlib as np

In [129]:
np.zeros((3,6))

matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [130]:
np.ones((2,3))

matrix([[1., 1., 1.],
        [1., 1., 1.]])

In [131]:
np.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])